import { FoodItemNutrition } from '../types';

export interface FoodCatalogEntry {
  name: string;
  aliases: string[];
  category: 'grain' | 'protein' | 'vegetable' | 'fruit' | 'dairy' | 'snack' | 'sweet' | 'beverage' | 'mixed';
  defaultPortionGrams: number;
  portionDescription: string;
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatPer100g: number;
  fiberPer100g: number;
  sugarPer100g: number;
  sodiumPer100g: number; // in mg
}

export const FOOD_DATABASE: FoodCatalogEntry[] = [
  // --- Indian Breads & Grains ---
  {
    name: 'Roti / Chapati (Whole Wheat)',
    aliases: ['roti', 'chapati', 'phulka', 'flatbread', 'wheat roti'],
    category: 'grain',
    defaultPortionGrams: 40,
    portionDescription: '1 medium roti (40g)',
    caloriesPer100g: 297,
    proteinPer100g: 9.3,
    carbsPer100g: 58.0,
    fatPer100g: 3.5,
    fiberPer100g: 9.2,
    sugarPer100g: 1.5,
    sodiumPer100g: 180,
  },
  {
    name: 'Butter Naan',
    aliases: ['naan', 'butter naan', 'tandoori naan', 'garlic naan'],
    category: 'grain',
    defaultPortionGrams: 90,
    portionDescription: '1 medium naan (90g)',
    caloriesPer100g: 310,
    proteinPer100g: 8.5,
    carbsPer100g: 50.0,
    fatPer100g: 9.0,
    fiberPer100g: 2.2,
    sugarPer100g: 3.0,
    sodiumPer100g: 450,
  },
  {
    name: 'Aloo Paratha',
    aliases: ['aloo paratha', 'potato paratha', 'stuffed paratha', 'paratha'],
    category: 'grain',
    defaultPortionGrams: 120,
    portionDescription: '1 paratha with butter (120g)',
    caloriesPer100g: 250,
    proteinPer100g: 5.2,
    carbsPer100g: 38.0,
    fatPer100g: 9.5,
    fiberPer100g: 3.8,
    sugarPer100g: 1.2,
    sodiumPer100g: 380,
  },
  {
    name: 'Steamed Basmati Rice',
    aliases: ['steamed rice', 'white rice', 'cooked rice', 'chawal', 'plain rice', 'basmati rice'],
    category: 'grain',
    defaultPortionGrams: 150,
    portionDescription: '1 medium bowl cooked (150g)',
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28.2,
    fatPer100g: 0.3,
    fiberPer100g: 0.4,
    sugarPer100g: 0.1,
    sodiumPer100g: 1,
  },
  {
    name: 'Brown Rice',
    aliases: ['brown rice', 'whole grain rice'],
    category: 'grain',
    defaultPortionGrams: 150,
    portionDescription: '1 medium bowl (150g)',
    caloriesPer100g: 111,
    proteinPer100g: 2.6,
    carbsPer100g: 23.0,
    fatPer100g: 0.9,
    fiberPer100g: 1.8,
    sugarPer100g: 0.4,
    sodiumPer100g: 5,
  },
  {
    name: 'Jeera Rice / Vegetable Pulao',
    aliases: ['jeera rice', 'pulao', 'veg pulao', 'cumin rice', 'pilaf'],
    category: 'grain',
    defaultPortionGrams: 180,
    portionDescription: '1 large bowl (180g)',
    caloriesPer100g: 165,
    proteinPer100g: 3.2,
    carbsPer100g: 29.5,
    fatPer100g: 3.8,
    fiberPer100g: 1.4,
    sugarPer100g: 0.8,
    sodiumPer100g: 220,
  },
  {
    name: 'Chicken Biryani',
    aliases: ['chicken biryani', 'dum biryani', 'hyderabadi biryani', 'biryani'],
    category: 'mixed',
    defaultPortionGrams: 300,
    portionDescription: '1 plate biryani with chicken (300g)',
    caloriesPer100g: 195,
    proteinPer100g: 9.8,
    carbsPer100g: 23.5,
    fatPer100g: 7.2,
    fiberPer100g: 1.2,
    sugarPer100g: 1.0,
    sodiumPer100g: 420,
  },
  {
    name: 'Paneer / Veg Biryani',
    aliases: ['veg biryani', 'paneer biryani', 'vegetable biryani'],
    category: 'mixed',
    defaultPortionGrams: 280,
    portionDescription: '1 plate veg biryani (280g)',
    caloriesPer100g: 178,
    proteinPer100g: 5.5,
    carbsPer100g: 26.0,
    fatPer100g: 6.0,
    fiberPer100g: 2.1,
    sugarPer100g: 1.4,
    sodiumPer100g: 390,
  },

  // --- Indian Dals & Curries ---
  {
    name: 'Yellow Dal Tadka (Toor / Moong)',
    aliases: ['dal tadka', 'yellow dal', 'dal fry', 'toor dal', 'moong dal', 'daal', 'dal'],
    category: 'protein',
    defaultPortionGrams: 160,
    portionDescription: '1 medium bowl (160g)',
    caloriesPer100g: 110,
    proteinPer100g: 5.8,
    carbsPer100g: 14.5,
    fatPer100g: 3.5,
    fiberPer100g: 3.4,
    sugarPer100g: 0.9,
    sodiumPer100g: 340,
  },
  {
    name: 'Dal Makhani',
    aliases: ['dal makhani', 'makhani dal', 'black dal', 'creamy dal'],
    category: 'protein',
    defaultPortionGrams: 180,
    portionDescription: '1 medium bowl with butter (180g)',
    caloriesPer100g: 155,
    proteinPer100g: 6.2,
    carbsPer100g: 16.0,
    fatPer100g: 7.8,
    fiberPer100g: 4.2,
    sugarPer100g: 1.5,
    sodiumPer100g: 410,
  },
  {
    name: 'Paneer Butter Masala',
    aliases: ['paneer butter masala', 'paneer makhani', 'shahi paneer', 'paneer curry'],
    category: 'protein',
    defaultPortionGrams: 180,
    portionDescription: '1 bowl with 5-6 paneer cubes (180g)',
    caloriesPer100g: 190,
    proteinPer100g: 8.5,
    carbsPer100g: 9.0,
    fatPer100g: 14.0,
    fiberPer100g: 1.8,
    sugarPer100g: 3.5,
    sodiumPer100g: 480,
  },
  {
    name: 'Palak Paneer',
    aliases: ['palak paneer', 'spinach paneer', 'saag paneer'],
    category: 'protein',
    defaultPortionGrams: 180,
    portionDescription: '1 bowl (180g)',
    caloriesPer100g: 145,
    proteinPer100g: 8.0,
    carbsPer100g: 6.2,
    fatPer100g: 10.5,
    fiberPer100g: 2.8,
    sugarPer100g: 1.8,
    sodiumPer100g: 390,
  },
  {
    name: 'Chole / Chana Masala',
    aliases: ['chole', 'chana masala', 'chickpea curry', 'punjabi chole'],
    category: 'protein',
    defaultPortionGrams: 180,
    portionDescription: '1 bowl chickpea curry (180g)',
    caloriesPer100g: 135,
    proteinPer100g: 6.5,
    carbsPer100g: 19.0,
    fatPer100g: 4.0,
    fiberPer100g: 4.8,
    sugarPer100g: 2.0,
    sodiumPer100g: 380,
  },
  {
    name: 'Rajma Masala (Red Kidney Beans)',
    aliases: ['rajma', 'rajma masala', 'kidney bean curry'],
    category: 'protein',
    defaultPortionGrams: 180,
    portionDescription: '1 bowl rajma (180g)',
    caloriesPer100g: 128,
    proteinPer100g: 6.8,
    carbsPer100g: 18.2,
    fatPer100g: 3.2,
    fiberPer100g: 5.1,
    sugarPer100g: 1.6,
    sodiumPer100g: 360,
  },
  {
    name: 'Chicken Curry (Homestyle)',
    aliases: ['chicken curry', 'desi chicken curry', 'tari chicken', 'murgh curry'],
    category: 'protein',
    defaultPortionGrams: 200,
    portionDescription: '1 bowl with 2 pieces chicken (200g)',
    caloriesPer100g: 145,
    proteinPer100g: 14.5,
    carbsPer100g: 4.2,
    fatPer100g: 7.8,
    fiberPer100g: 1.1,
    sugarPer100g: 1.2,
    sodiumPer100g: 430,
  },
  {
    name: 'Butter Chicken (Murgh Makhani)',
    aliases: ['butter chicken', 'murgh makhani', 'creamy chicken curry'],
    category: 'protein',
    defaultPortionGrams: 220,
    portionDescription: '1 bowl creamy chicken (220g)',
    caloriesPer100g: 198,
    proteinPer100g: 13.8,
    carbsPer100g: 7.5,
    fatPer100g: 13.0,
    fiberPer100g: 1.0,
    sugarPer100g: 3.2,
    sodiumPer100g: 520,
  },
  {
    name: 'Egg Curry (2 Eggs)',
    aliases: ['egg curry', 'anda curry', 'egg gravy', 'dimer jhol'],
    category: 'protein',
    defaultPortionGrams: 200,
    portionDescription: '1 bowl with 2 boiled eggs (200g)',
    caloriesPer100g: 130,
    proteinPer100g: 8.5,
    carbsPer100g: 5.0,
    fatPer100g: 8.6,
    fiberPer100g: 1.0,
    sugarPer100g: 1.4,
    sodiumPer100g: 370,
  },
  {
    name: 'Mix Vegetable Sabzi (Bhindi/Gobi/Aloo)',
    aliases: ['mix veg', 'sabzi', 'bhindi', 'aloo gobi', 'gobi masala', 'dry vegetable'],
    category: 'vegetable',
    defaultPortionGrams: 150,
    portionDescription: '1 medium bowl dry sabzi (150g)',
    caloriesPer100g: 95,
    proteinPer100g: 2.8,
    carbsPer100g: 12.0,
    fatPer100g: 4.2,
    fiberPer100g: 3.6,
    sugarPer100g: 2.5,
    sodiumPer100g: 310,
  },

  // --- Indian Dairy, Sides & Accompaniments ---
  {
    name: 'Plain Curd / Dahi (Yogurt)',
    aliases: ['curd', 'dahi', 'yogurt', 'plain dahi', 'hung curd', 'homemade curd'],
    category: 'dairy',
    defaultPortionGrams: 120,
    portionDescription: '1 small katori (120g)',
    caloriesPer100g: 65,
    proteinPer100g: 3.8,
    carbsPer100g: 4.7,
    fatPer100g: 3.5,
    fiberPer100g: 0,
    sugarPer100g: 4.5,
    sodiumPer100g: 45,
  },
  {
    name: 'Cucumber Boondi Raita',
    aliases: ['raita', 'boondi raita', 'cucumber raita', 'onion raita'],
    category: 'dairy',
    defaultPortionGrams: 120,
    portionDescription: '1 small bowl (120g)',
    caloriesPer100g: 82,
    proteinPer100g: 3.2,
    carbsPer100g: 7.5,
    fatPer100g: 4.2,
    fiberPer100g: 0.5,
    sugarPer100g: 3.8,
    sodiumPer100g: 180,
  },
  {
    name: 'Green Salad (Cucumber, Tomato, Onion)',
    aliases: ['green salad', 'kachumber salad', 'cucumber salad', 'kachumber', 'salad'],
    category: 'vegetable',
    defaultPortionGrams: 100,
    portionDescription: '1 plate raw cut salad with lemon (100g)',
    caloriesPer100g: 24,
    proteinPer100g: 1.1,
    carbsPer100g: 4.8,
    fatPer100g: 0.2,
    fiberPer100g: 1.6,
    sugarPer100g: 2.4,
    sodiumPer100g: 25,
  },
  {
    name: 'Papad (Roasted)',
    aliases: ['papad', 'roasted papad', 'papadum', 'appalam'],
    category: 'snack',
    defaultPortionGrams: 15,
    portionDescription: '1 medium roasted papad (15g)',
    caloriesPer100g: 340,
    proteinPer100g: 22.0,
    carbsPer100g: 56.0,
    fatPer100g: 2.0,
    fiberPer100g: 8.0,
    sugarPer100g: 1.0,
    sodiumPer100g: 1400,
  },

  // --- South Indian Breakfasts ---
  {
    name: 'Masala Dosa with Sambar & Chutney',
    aliases: ['masala dosa', 'dosa', 'plain dosa', 'ghee roast dosa'],
    category: 'mixed',
    defaultPortionGrams: 180,
    portionDescription: '1 large crispy masala dosa (180g)',
    caloriesPer100g: 185,
    proteinPer100g: 4.2,
    carbsPer100g: 28.0,
    fatPer100g: 6.5,
    fiberPer100g: 2.4,
    sugarPer100g: 1.5,
    sodiumPer100g: 390,
  },
  {
    name: 'Steamed Idli (2 pieces)',
    aliases: ['idli', 'steamed idli', 'rice idli', 'idly'],
    category: 'grain',
    defaultPortionGrams: 100,
    portionDescription: '2 pieces medium idli (100g)',
    caloriesPer100g: 135,
    proteinPer100g: 4.5,
    carbsPer100g: 27.0,
    fatPer100g: 0.8,
    fiberPer100g: 1.8,
    sugarPer100g: 0.6,
    sodiumPer100g: 210,
  },
  {
    name: 'Vegetable Sambar',
    aliases: ['sambar', 'sambhar', 'drumstick sambar', 'lentil stew'],
    category: 'protein',
    defaultPortionGrams: 150,
    portionDescription: '1 medium bowl (150g)',
    caloriesPer100g: 65,
    proteinPer100g: 3.2,
    carbsPer100g: 9.8,
    fatPer100g: 1.6,
    fiberPer100g: 2.6,
    sugarPer100g: 2.1,
    sodiumPer100g: 310,
  },
  {
    name: 'Coconut Chutney',
    aliases: ['coconut chutney', 'nariyal chutney', 'white chutney'],
    category: 'dairy',
    defaultPortionGrams: 40,
    portionDescription: '2 tablespoons (40g)',
    caloriesPer100g: 230,
    proteinPer100g: 3.0,
    carbsPer100g: 8.5,
    fatPer100g: 21.0,
    fiberPer100g: 4.0,
    sugarPer100g: 2.8,
    sodiumPer100g: 340,
  },
  {
    name: 'Poha with Peanuts',
    aliases: ['poha', 'flattened rice', 'kanda poha', 'aval'],
    category: 'grain',
    defaultPortionGrams: 160,
    portionDescription: '1 medium plate (160g)',
    caloriesPer100g: 160,
    proteinPer100g: 4.1,
    carbsPer100g: 26.5,
    fatPer100g: 4.5,
    fiberPer100g: 2.1,
    sugarPer100g: 1.4,
    sodiumPer100g: 280,
  },
  {
    name: 'Upma (Rava / Semolina)',
    aliases: ['upma', 'rava upma', 'sooji upma', 'sanja'],
    category: 'grain',
    defaultPortionGrams: 160,
    portionDescription: '1 bowl upma (160g)',
    caloriesPer100g: 145,
    proteinPer100g: 3.8,
    carbsPer100g: 23.0,
    fatPer100g: 4.2,
    fiberPer100g: 1.8,
    sugarPer100g: 1.0,
    sodiumPer100g: 290,
  },

  // --- Western, Global & Fitness Staples ---
  {
    name: 'Avocado Toast with Poached Egg',
    aliases: ['avocado toast', 'egg on toast', 'sourdough avocado toast', 'avo toast'],
    category: 'mixed',
    defaultPortionGrams: 175,
    portionDescription: '1 slice sourdough + 1/2 avocado + 1 egg (175g)',
    caloriesPer100g: 195,
    proteinPer100g: 7.4,
    carbsPer100g: 16.5,
    fatPer100g: 11.2,
    fiberPer100g: 4.5,
    sugarPer100g: 1.2,
    sodiumPer100g: 290,
  },
  {
    name: 'Grilled Salmon with Quinoa & Asparagus',
    aliases: ['grilled salmon', 'salmon bowl', 'salmon with quinoa', 'baked salmon'],
    category: 'mixed',
    defaultPortionGrams: 280,
    portionDescription: '1 fillet salmon (150g) + quinoa & greens (280g total)',
    caloriesPer100g: 170,
    proteinPer100g: 16.5,
    carbsPer100g: 10.2,
    fatPer100g: 7.2,
    fiberPer100g: 2.2,
    sugarPer100g: 0.8,
    sodiumPer100g: 190,
  },
  {
    name: 'Grilled Chicken Breast',
    aliases: ['grilled chicken', 'chicken breast', 'baked chicken breast', 'lean chicken'],
    category: 'protein',
    defaultPortionGrams: 150,
    portionDescription: '1 skinless grilled breast (150g)',
    caloriesPer100g: 165,
    proteinPer100g: 31.0,
    carbsPer100g: 0,
    fatPer100g: 3.6,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 74,
  },
  {
    name: 'Whole Boiled / Scrambled Eggs (2)',
    aliases: ['boiled egg', 'boiled eggs', 'scrambled eggs', 'fried egg', 'omelette', 'eggs'],
    category: 'protein',
    defaultPortionGrams: 100,
    portionDescription: '2 large eggs (100g)',
    caloriesPer100g: 155,
    proteinPer100g: 13.0,
    carbsPer100g: 1.1,
    fatPer100g: 11.0,
    fiberPer100g: 0,
    sugarPer100g: 1.1,
    sodiumPer100g: 124,
  },
  {
    name: 'Egg Whites (3 whites)',
    aliases: ['egg white', 'egg whites', 'boiled egg white'],
    category: 'protein',
    defaultPortionGrams: 100,
    portionDescription: '3 egg whites (100g)',
    caloriesPer100g: 52,
    proteinPer100g: 11.0,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    fiberPer100g: 0,
    sugarPer100g: 0.7,
    sodiumPer100g: 166,
  },
  {
    name: 'Rolled Oatmeal with Berries & Almonds',
    aliases: ['oatmeal', 'oats', 'porridge', 'oat bowl', 'overnight oats'],
    category: 'grain',
    defaultPortionGrams: 220,
    portionDescription: '1 bowl cooked oats + toppings (220g)',
    caloriesPer100g: 125,
    proteinPer100g: 4.8,
    carbsPer100g: 21.0,
    fatPer100g: 3.0,
    fiberPer100g: 3.6,
    sugarPer100g: 5.5,
    sodiumPer100g: 45,
  },
  {
    name: 'Greek Yogurt with Honey & Blueberries',
    aliases: ['greek yogurt', 'strained yogurt', 'yogurt bowl', 'parfait'],
    category: 'dairy',
    defaultPortionGrams: 180,
    portionDescription: '1 bowl plain Greek yogurt + honey & berries (180g)',
    caloriesPer100g: 95,
    proteinPer100g: 8.5,
    carbsPer100g: 9.8,
    fatPer100g: 2.2,
    fiberPer100g: 0.8,
    sugarPer100g: 8.5,
    sodiumPer100g: 42,
  },
  {
    name: 'Whey Protein Shake (1 Scoop + Water/Milk)',
    aliases: ['protein shake', 'whey protein', 'protein drink', 'protein smoothie'],
    category: 'protein',
    defaultPortionGrams: 300,
    portionDescription: '1 shaker bottle (300ml)',
    caloriesPer100g: 50,
    proteinPer100g: 8.0,
    carbsPer100g: 2.0,
    fatPer100g: 0.8,
    fiberPer100g: 0.4,
    sugarPer100g: 1.5,
    sodiumPer100g: 65,
  },
  {
    name: 'Tofu / Paneer Tikka Stir Fry',
    aliases: ['tofu stir fry', 'tofu', 'paneer tikka', 'grilled paneer', 'soya chunks curry'],
    category: 'protein',
    defaultPortionGrams: 160,
    portionDescription: '1 plate grilled tikka (160g)',
    caloriesPer100g: 165,
    proteinPer100g: 14.2,
    carbsPer100g: 6.5,
    fatPer100g: 9.5,
    fiberPer100g: 2.2,
    sugarPer100g: 2.0,
    sodiumPer100g: 340,
  },
  {
    name: 'Mediterranean Chickpea & Feta Salad',
    aliases: ['chickpea salad', 'greek salad', 'mediterranean salad', 'caesar salad'],
    category: 'vegetable',
    defaultPortionGrams: 200,
    portionDescription: '1 large salad bowl (200g)',
    caloriesPer100g: 135,
    proteinPer100g: 5.6,
    carbsPer100g: 14.5,
    fatPer100g: 6.8,
    fiberPer100g: 3.8,
    sugarPer100g: 2.6,
    sodiumPer100g: 320,
  },

  // --- Fresh Fruits & Healthy Snacks ---
  {
    name: 'Fresh Banana (Medium)',
    aliases: ['banana', 'kela', 'ripe banana'],
    category: 'fruit',
    defaultPortionGrams: 118,
    portionDescription: '1 medium banana (118g)',
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatPer100g: 0.3,
    fiberPer100g: 2.6,
    sugarPer100g: 12.2,
    sodiumPer100g: 1,
  },
  {
    name: 'Fresh Apple (Medium)',
    aliases: ['apple', 'red apple', 'green apple', 'seb'],
    category: 'fruit',
    defaultPortionGrams: 150,
    portionDescription: '1 medium apple (150g)',
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    fiberPer100g: 2.4,
    sugarPer100g: 10.4,
    sodiumPer100g: 1,
  },
  {
    name: 'Mixed Raw Almonds & Walnuts',
    aliases: ['almonds', 'nuts', 'walnuts', 'badam', 'akhrot', 'mixed nuts'],
    category: 'snack',
    defaultPortionGrams: 30,
    portionDescription: '1 small handful (~15-18 nuts, 30g)',
    caloriesPer100g: 607,
    proteinPer100g: 18.5,
    carbsPer100g: 17.0,
    fatPer100g: 54.0,
    fiberPer100g: 9.8,
    sugarPer100g: 3.8,
    sodiumPer100g: 2,
  },
  {
    name: 'Chai / Milk Tea (Indian Style with 1 tsp sugar)',
    aliases: ['chai', 'tea', 'milk tea', 'masala chai', 'ginger tea'],
    category: 'beverage',
    defaultPortionGrams: 150,
    portionDescription: '1 cup (150ml)',
    caloriesPer100g: 60,
    proteinPer100g: 2.0,
    carbsPer100g: 8.5,
    fatPer100g: 2.1,
    fiberPer100g: 0,
    sugarPer100g: 7.5,
    sodiumPer100g: 35,
  },
  {
    name: 'Black Coffee / Green Tea (Unsweetened)',
    aliases: ['black coffee', 'green tea', 'espresso', 'black tea', 'americano'],
    category: 'beverage',
    defaultPortionGrams: 200,
    portionDescription: '1 cup / mug (200ml)',
    caloriesPer100g: 2,
    proteinPer100g: 0.1,
    carbsPer100g: 0.2,
    fatPer100g: 0,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 4,
  }
];

export function lookupFoodByQuery(query: string): FoodCatalogEntry[] {
  const clean = query.trim().toLowerCase();
  if (!clean) return FOOD_DATABASE.slice(0, 15);

  return FOOD_DATABASE.filter(f => {
    if (f.name.toLowerCase().includes(clean)) return true;
    return f.aliases.some(alias => alias.includes(clean) || clean.includes(alias));
  });
}

export function convertEntryToNutritionItem(entry: FoodCatalogEntry, portionGrams?: number): FoodItemNutrition {
  const grams = portionGrams ?? entry.defaultPortionGrams;
  const ratio = grams / 100;

  return {
    id: `food-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`,
    name: entry.name,
    portionGrams: Math.round(grams),
    portionDescription: `${grams}g (${Math.round((grams / entry.defaultPortionGrams) * 10) / 10}x standard)`,
    calories: Math.round(entry.caloriesPer100g * ratio),
    protein: Number((entry.proteinPer100g * ratio).toFixed(1)),
    carbs: Number((entry.carbsPer100g * ratio).toFixed(1)),
    fat: Number((entry.fatPer100g * ratio).toFixed(1)),
    fiber: Number((entry.fiberPer100g * ratio).toFixed(1)),
    sugar: Number((entry.sugarPer100g * ratio).toFixed(1)),
    sodium: Math.round(entry.sodiumPer100g * ratio),
    category: entry.category,
    confidence: 0.95,
  };
}

// Preset Multi-Item Sample Meal Plates for instant camera & photo testing
export interface PresetSampleMeal {
  id: string;
  name: string;
  category: string;
  subtitle: string;
  photoUrl: string;
  items: {
    name: string;
    portionGrams: number;
    portionDescription: string;
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
    sugar: number;
    sodium: number;
    category: 'grain' | 'protein' | 'vegetable' | 'fruit' | 'dairy' | 'snack';
    plateLocation: string;
    boundingBox: { ymin: number; xmin: number; ymax: number; xmax: number };
  }[];
}

export const PRESET_SAMPLE_MEALS: PresetSampleMeal[] = [
  {
    id: 'sample-indian-thali',
    name: 'Traditional North Indian Thali',
    category: 'lunch',
    subtitle: 'Roti, Dal Tadka, Paneer Masala, Basmati Rice, Dahi & Salad',
    photoUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        name: 'Whole Wheat Roti (2 pcs)',
        portionGrams: 80,
        portionDescription: '2 medium rotis (80g)',
        calories: 238,
        protein: 7.4,
        carbs: 46.4,
        fat: 2.8,
        fiber: 7.4,
        sugar: 1.2,
        sodium: 144,
        category: 'grain',
        plateLocation: 'Top Left',
        boundingBox: { ymin: 15, xmin: 10, ymax: 48, xmax: 45 }
      },
      {
        name: 'Steamed Basmati Rice',
        portionGrams: 150,
        portionDescription: '1 medium bowl (150g)',
        calories: 195,
        protein: 4.1,
        carbs: 42.3,
        fat: 0.5,
        fiber: 0.6,
        sugar: 0.2,
        sodium: 2,
        category: 'grain',
        plateLocation: 'Center',
        boundingBox: { ymin: 40, xmin: 35, ymax: 75, xmax: 65 }
      },
      {
        name: 'Yellow Dal Tadka',
        portionGrams: 150,
        portionDescription: '1 katori dal (150g)',
        calories: 165,
        protein: 8.7,
        carbs: 21.8,
        fat: 5.3,
        fiber: 5.1,
        sugar: 1.4,
        sodium: 510,
        category: 'protein',
        plateLocation: 'Top Right Bowl',
        boundingBox: { ymin: 10, xmin: 55, ymax: 42, xmax: 90 }
      },
      {
        name: 'Paneer Butter Masala',
        portionGrams: 160,
        portionDescription: '1 katori curry (160g)',
        calories: 304,
        protein: 13.6,
        carbs: 14.4,
        fat: 22.4,
        fiber: 2.9,
        sugar: 5.6,
        sodium: 768,
        category: 'protein',
        plateLocation: 'Right Center Bowl',
        boundingBox: { ymin: 45, xmin: 68, ymax: 82, xmax: 95 }
      },
      {
        name: 'Fresh Plain Curd (Dahi)',
        portionGrams: 100,
        portionDescription: '1 small katori (100g)',
        calories: 65,
        protein: 3.8,
        carbs: 4.7,
        fat: 3.5,
        fiber: 0,
        sugar: 4.5,
        sodium: 45,
        category: 'dairy',
        plateLocation: 'Bottom Center Bowl',
        boundingBox: { ymin: 72, xmin: 40, ymax: 95, xmax: 65 }
      },
      {
        name: 'Green Salad (Cucumber & Onion)',
        portionGrams: 60,
        portionDescription: 'Small side salad (60g)',
        calories: 15,
        protein: 0.7,
        carbs: 2.9,
        fat: 0.1,
        fiber: 1.0,
        sugar: 1.5,
        sodium: 15,
        category: 'vegetable',
        plateLocation: 'Bottom Left',
        boundingBox: { ymin: 60, xmin: 12, ymax: 90, xmax: 38 }
      }
    ]
  },
  {
    id: 'sample-avocado-breakfast',
    name: 'Sourdough Avocado & Poached Eggs',
    category: 'breakfast',
    subtitle: 'Artisan sourdough, smashed Hass avocado, 2 poached eggs & cherry tomatoes',
    photoUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        name: 'Toasted Sourdough Slice (2 pcs)',
        portionGrams: 80,
        portionDescription: '2 slices toasted (80g)',
        calories: 216,
        protein: 7.2,
        carbs: 42.0,
        fat: 1.6,
        fiber: 2.4,
        sugar: 1.6,
        sodium: 440,
        category: 'grain',
        plateLocation: 'Base',
        boundingBox: { ymin: 25, xmin: 20, ymax: 75, xmax: 80 }
      },
      {
        name: 'Smashed Hass Avocado',
        portionGrams: 80,
        portionDescription: '1/2 medium avocado (80g)',
        calories: 128,
        protein: 1.6,
        carbs: 6.8,
        fat: 11.7,
        fiber: 5.4,
        sugar: 0.5,
        sodium: 6,
        category: 'fruit',
        plateLocation: 'Spread on Toast',
        boundingBox: { ymin: 30, xmin: 25, ymax: 70, xmax: 75 }
      },
      {
        name: 'Organic Poached Eggs (2 pcs)',
        portionGrams: 100,
        portionDescription: '2 whole poached eggs (100g)',
        calories: 143,
        protein: 12.6,
        carbs: 0.7,
        fat: 9.5,
        fiber: 0,
        sugar: 0.7,
        sodium: 142,
        category: 'protein',
        plateLocation: 'Top of Toast',
        boundingBox: { ymin: 35, xmin: 35, ymax: 65, xmax: 65 }
      },
      {
        name: 'Roasted Cherry Tomatoes & Microgreens',
        portionGrams: 60,
        portionDescription: 'Side garnish (60g)',
        calories: 18,
        protein: 0.8,
        carbs: 3.5,
        fat: 0.2,
        fiber: 1.2,
        sugar: 2.3,
        sodium: 12,
        category: 'vegetable',
        plateLocation: 'Plate Rim',
        boundingBox: { ymin: 15, xmin: 65, ymax: 45, xmax: 90 }
      }
    ]
  },
  {
    id: 'sample-grilled-salmon',
    name: 'Grilled Salmon Power Bowl',
    category: 'dinner',
    subtitle: 'Wild Atlantic salmon fillet, tri-color quinoa, roasted broccoli & lemon dill',
    photoUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        name: 'Grilled Salmon Fillet',
        portionGrams: 160,
        portionDescription: '1 center-cut fillet (160g)',
        calories: 332,
        protein: 34.0,
        carbs: 0,
        fat: 20.0,
        fiber: 0,
        sugar: 0,
        sodium: 120,
        category: 'protein',
        plateLocation: 'Center Right',
        boundingBox: { ymin: 25, xmin: 45, ymax: 75, xmax: 85 }
      },
      {
        name: 'Cooked Quinoa',
        portionGrams: 130,
        portionDescription: '1 cup cooked (130g)',
        calories: 156,
        protein: 5.7,
        carbs: 27.6,
        fat: 2.5,
        fiber: 3.6,
        sugar: 1.1,
        sodium: 9,
        category: 'grain',
        plateLocation: 'Bottom Left',
        boundingBox: { ymin: 50, xmin: 15, ymax: 85, xmax: 50 }
      },
      {
        name: 'Steamed Broccoli & Edamame',
        portionGrams: 100,
        portionDescription: '1 cup florets (100g)',
        calories: 45,
        protein: 3.8,
        carbs: 7.2,
        fat: 0.6,
        fiber: 3.3,
        sugar: 1.8,
        sodium: 35,
        category: 'vegetable',
        plateLocation: 'Top Left',
        boundingBox: { ymin: 15, xmin: 15, ymax: 48, xmax: 50 }
      }
    ]
  },
  {
    id: 'sample-south-indian-dosa',
    name: 'Crispy Masala Dosa Platter',
    category: 'breakfast',
    subtitle: 'Golden dosa stuffed with potato masala, piping hot sambar & coconut chutney',
    photoUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    items: [
      {
        name: 'Crispy Masala Dosa (Potato Stuffed)',
        portionGrams: 180,
        portionDescription: '1 large crisp dosa (180g)',
        calories: 335,
        protein: 7.6,
        carbs: 50.4,
        fat: 11.7,
        fiber: 4.3,
        sugar: 2.7,
        sodium: 702,
        category: 'grain',
        plateLocation: 'Center Platter',
        boundingBox: { ymin: 15, xmin: 10, ymax: 85, xmax: 65 }
      },
      {
        name: 'Vegetable Sambar',
        portionGrams: 150,
        portionDescription: '1 bowl vegetable sambar (150g)',
        calories: 98,
        protein: 4.8,
        carbs: 14.7,
        fat: 2.4,
        fiber: 3.9,
        sugar: 3.2,
        sodium: 465,
        category: 'protein',
        plateLocation: 'Top Right Bowl',
        boundingBox: { ymin: 15, xmin: 70, ymax: 48, xmax: 95 }
      },
      {
        name: 'Fresh Coconut Chutney',
        portionGrams: 50,
        portionDescription: '2.5 tablespoons (50g)',
        calories: 115,
        protein: 1.5,
        carbs: 4.3,
        fat: 10.5,
        fiber: 2.0,
        sugar: 1.4,
        sodium: 170,
        category: 'dairy',
        plateLocation: 'Bottom Right Bowl',
        boundingBox: { ymin: 52, xmin: 70, ymax: 85, xmax: 95 }
      }
    ]
  }
];
